language: c
before_install:
  - sudo apt-get install valgrind
  - git clone https://github.com/LukeMS/absdatatypes-c.git
  - git clone https://github.com/LukeMS/zhash-c.git
install:
  - cd absdatatypes-c && make install --file=linux.makefile && cd..
  - cd zhash-c && make install --file=linux.makefile && cd..
  - sudo make install --file=linux.makefile
script:
  - cd test01 && make valgrind --file=linux.makefile && cd..
after_script: